version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - nghia:/app/upload/
    ports:
    - "8080:8080"

  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./tmp:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  nghia: